### ISSUE TITLE
Replace mirror.pkgbuild.com with geo.mirror.pkgbuild.com

### ISSUE THREAD

**Issue by nl6720** [BlackArch/blackarch-docker#10]
https://github.com/BlackArch/blackarch-docker/blob/802d36c0645d7372b475b7f215403e8df5e604a0/rootfs/etc/pacman.d/mirrorlist#L1

mirror.pkgbuild.com is [not public](https://archlinux.org/mirrors/mirror.pkgbuild.com/). Using it generates excessive traffic to Arch's infrastructure.

Its replacement is [geo.mirror.pkgbuild.com](https://geo.mirror.pkgbuild.com/). See https://gitlab.archlinux.org/archlinux/infrastructure/-/merge_requests/522 for details.

**Comment by ikstream** [comment]
Thank you for pointing this out.
