### ISSUE TITLE
Getting unknown trust on BlackArch key when BlackArch docker is trying to generate

### ISSUE THREAD

**Issue by D3vil0p3r** [BlackArch/blackarch-docker#17]
GitHub workflows of BlackArch Docker is getting error due to:
```
error: blackarch: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" is unknown trust
```
Source: https://github.com/BlackArch/blackarch-docker/actions/runs/7079778429/job/19266789018

Getting same issue also on Arch with BlackArch repo.

**Comment by noraj** [comment]
see also https://github.com/BlackArch/blackarch/issues?q=is%3Aissue+error%3A+blackarch%3A+signature+from+%27Levon+%27noptrix%27+Kayan+%28BlackArch+Developer%29

**Comment by ikstream** [comment]
Should be fixed
